[tools]
bun = "1.3.1"
deno = "2.5.6"
neovim = "0.11.5"
usage = "2.3.2"
uv = "0.9.7"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:ClementTsang/bottom" = "0.11.2"
"aqua:aws-cli" = "2.31.29"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:bootandy/dust" = "1.2.3"
"aqua:casey/just" = "1.43.0"
"aqua:chmln/sd" = "1.0.0"
"aqua:dandavison/delta" = "0.18.2"
"aqua:direnv/direnv" = "2.37.1"
"aqua:gh" = "2.83.0"
"aqua:ismaelgv/rnr" = "0.5.0"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.66.1"
"aqua:mikefarah/yq" = "4.48.1"
"aqua:rossmacarthur/sheldon" = "0.8.5"
"aqua:sharkdp/bat" = "0.26.0"
"aqua:sharkdp/fd" = "10.3.0"
"aqua:typst/typst" = "0.13.1"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:ccusage" = "17.1.3"
"npm:difit" = "2.2.2"
"npm:serve" = "14.2.5"
"npm:typescript-language-server" = "5.1.3"
"pipx:httpie" = "3.2.4"
"pipx:thefuck" = { version = "3.32", uvx_args = "--python 3.8" }
"pipx:trash-cli" = "0.24.5.26"
"pipx:python-lsp-server" = "1.13.1"
"ubi:d-kuro/gwq" = "0.0.5"

[settings]
aqua.cosign = true
npm.bun = true
pipx.uvx = true
idiomatic_version_file_enable_tools = []
