[tools]
bun = "1.3.6"
deno = "2.6.5"
neovim = "0.11.5"
usage = "2.12.0"
uv = "0.9.26"
"aqua:BurntSushi/ripgrep" = "15.1.0"
"aqua:ClementTsang/bottom" = "0.12.3"
"aqua:aws-cli" = "2.33.2"
"aqua:ajeetdsouza/zoxide" = "0.9.8"
"aqua:bootandy/dust" = "1.2.4"
"aqua:casey/just" = "1.46.0"
"aqua:chmln/sd" = "1.0.0"
"aqua:dandavison/delta" = "0.18.2"
"aqua:direnv/direnv" = "2.37.1"
"aqua:gh" = "2.85.0"
"aqua:ismaelgv/rnr" = "0.5.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:junegunn/fzf" = "0.67.0"
"aqua:koalaman/shellcheck" = "0.11.0"
"aqua:mikefarah/yq" = "4.50.1"
"aqua:rossmacarthur/sheldon" = "0.8.5"
"aqua:sharkdp/bat" = "0.26.1"
"aqua:sharkdp/fd" = "10.3.0"
"aqua:typst/typst" = "0.14.2"
"npm:@google/gemini-cli" = "0.24.0"
"npm:@marp-team/marp-cli" = "4.2.3"
"npm:ccusage" = "18.0.5"
"npm:difit" = "3.0.2"
"npm:serve" = "14.2.5"
"npm:typescript-language-server" = "5.1.3"
"pipx:httpie" = "3.2.4"
"pipx:thefuck" = { version = "3.32", uvx_args = "--python 3.8" }
"pipx:trash-cli" = "0.24.5.26"
"pipx:python-lsp-server" = "1.14.0"
"ubi:d-kuro/gwq" = "0.0.11"

[settings]
aqua.cosign = true
npm.bun = true
pipx.uvx = true
idiomatic_version_file_enable_tools = []
